services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\About\:
    resource: '../Classes/*'

  TYPO3\CMS\About\Controller\AboutController:
    tags: ['backend.controller']
